### ISSUE TITLE
Add the possibility to choose how to obscure card number

### ISSUE THREAD

**Issue by baptistesx** [SimformSolutionsPvtLtd/flutter_credit_card#108]
I'd like to obscure the full card number except the last 4 chars:
![image](https://user-images.githubusercontent.com/9638281/193312129-11bd0bf8-cb71-49b8-9a60-9f8d34c65322.png)

I guess it would be replacing this hard coded value with a param?
![image](https://user-images.githubusercontent.com/9638281/193312703-7a9d145e-1f75-41a1-a6ce-12878c47cf56.png)

**Comment by kavantrivedi** [comment]
Hi, @baptistesx Thank you for the suggestion, We'll consider this enhancement in the next feature bucket. Also, we are open for contributions as well.

**Comment by baptistesx** [comment]
Still in the rush about work..., but i'm thinking about contributing to open sources projects now i get a better level at Flutter dev!
