### ISSUE TITLE
News Credit Card Num Pattern

### ISSUE THREAD

**Issue by fhariano** [SimformSolutionsPvtLtd/flutter_credit_card#119]
Hey, guys!

I detected that in the card number pattern list, there is still a need to adjust:
- The Hipercard pattern are only the initial numbers 38 and 60;
- ELO just add these patterns: 4011, 4576 and 5067.

Thanks!

**Comment by ShwetaChauhan18** [comment]
@fhariano: Please check our new release and let us know if you still face issue.

**Comment by vatsaltanna** [comment]
Closing this for now, feel free to reopen this if this issue still persist in latest release.
