### ISSUE TITLE
keyboardType: TextInputType.number not working on iOS for cardNumber

### ISSUE THREAD

**Issue by baptistesx** [SimformSolutionsPvtLtd/flutter_credit_card#126]
Heyy!
I have no clue why keyboardType: TextInputType.number is not working on iOS for cardNumber. It is working as expected on android.
 Here is a demo: 

https://user-images.githubusercontent.com/9638281/215932899-e6fc9a41-cfa7-4ec1-b511-56bb86b0b7a7.mov

I can see in the package code /flutter_credit_card-3.0.5/lib/credit_card_form.dart line 194, the keyboardType prop is well setup
![image](https://user-images.githubusercontent.com/9638281/215933388-d8c84b96-4c66-419a-89f3-4eba92cb4439.png)

Any idea?

**Comment by adamcastleman** [comment]
AutofillHints.creditCardNumber overrides and displays number + options. Delete the autofill hint variable entirely and the keyboard type will display just the numbers.

Use the hintText under the InputDecoration if you still need the hint.

**Comment by baptistesx** [comment]
thanks @adamcastleman  for your answer.

You mean remove it like this?
![image](https://user-images.githubusercontent.com/9638281/216345999-623cb991-0b1b-42df-b9fa-95e3851ca278.png)

But it's in the packge, i cannot touch it, except if if copy it locally but then it won't be linked to pub anymore, that's not good. Or i miss something?

**Comment by adamcastleman** [comment]
Right - you could copy to a local file. The form is just a StatefulWidget. It would still interact with the card widget.

You do lose access to pub updates. This may not really be all bad for the form - how often does a form entering CC info need to radically change?

You could also file a pull request and change the hardcoded value to softcode and feed it into the widget. 

Or hopefully, a package manager is seeing this and can submit a pull request themselves.

The number + options was just annoying enough for me to decide to copy over the form. It also let me clean it up. You'll have to decide for your own app.

**Comment by baptistesx** [comment]
Thank you, it took me 45s! I hope one day, i'll have time to do a PR...
