### ISSUE TITLE
Error-holderName

### ISSUE THREAD

**Issue by rafaeIpereira** [SimformSolutionsPvtLtd/flutter_credit_card#143]
**Describe the bug**
I enter to credit_card - holderName but don't seem credit_card holderName in credit_card. 
How to fix this problem ?

**Expected behavior**
My input name does not appear in the card animation

**Screenshots**
![WhatsApp Image 2023-06-29 at 20 36 49](https://github.co
![WhatsApp Image 2023-06-29 at 20 40 35](https://github.com/SimformSolutionsPvtLtd/flutter_credit_card/assets/84694194/d88b67f0-bf1f-4527-9c58-8088bfbd521e)
m/SimformSolutionsPvtLtd/flutter_credit_card/assets/84694194/8360a885-5341-4407-abc6-aec6200701af)

**Desktop (please complete the following information):**
 -OS(e.g. iOS)
 -Browser(e.g. chrome, safari)
 -Version(e.g. 22)

**Smartphone (please complete the following information):**
 -Device: Galaxy
 -Version(flutter_credit_card: ^3.0.7)

**Comment by vatsaltanna** [comment]
Hi, @rafaeIpereira I have tried to replicate this issue in the latest version, but it's working fine in the example. Are you updating the widget on the callback of `onCreditCardModelChange: (cardDetails)` ? Please take a reference from the example.

**Comment by rafaeIpereira** [comment]
Yes, I did it! See my code please. I believe it's correct, I'm using the lastest version this package (flutter_credit_card: ^3.0.7)
.
.
.
.
.
![flutter_credit_card](https://github.com/SimformSolutionsPvtLtd/flutter_credit_card/assets/84694194/dd51ef6c-3a80-4116-b08c-ce7f6071e32c)

**Comment by aditya-chavda** [comment]
Hey @rafaeIpereira, thanks for sharing your code!

Upon reviewing your code, I noticed a minor detail that I believe is worth bringing to your attention. It appears that `isHolderNameVisible` is set to `false` as the default value in the `CreditCardWidget`. To ensure that the card holder's name is displayed, kindly consider utilizing `isHolderNameVisible: true` when using the `CreditCardWidget`.

Please don't hesitate to return if you encounter any challenges or require further assistance following the adjustment mentioned above.

**Comment by vatsaltanna** [comment]
Hi @rafaeIpereira , I hope the solution provided by @aditya-chavda  will solve your problem. I am closing this issue. Feel free to reopen this issue if the issue still persists.
