### ISSUE TITLE
Change hint Color and enabled border color

### ISSUE THREAD

**Issue by jawad12345A** [SimformSolutionsPvtLtd/flutter_credit_card#15]
**Change hint and enabled color*
I want to change the color of hint and enable border but there is no param for it. 
![Screenshot_1583479773](https://user-images.githubusercontent.com/29260467/76062620-dd961880-5fa7-11ea-8d81-71b28e5f52e0.png)

**Comment by DevarshRanpara** [comment]
Will be fixed in #22 .
