### ISSUE TITLE
Exception when closing the page with the CreditCardWidget (Bad state: Cannot add new events after calling close)

### ISSUE THREAD

**Issue by orangeyong** [SimformSolutionsPvtLtd/flutter_credit_card#157]
When pop/closing the page with the CreditCardWidget, my Crashlytics is able to catch this error.

flutter: Bad state: Cannot add new events after calling close
flutter: 
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      _CreditCardWidgetState._processFloatingEvent (package:flutter_credit_card/src/credit_card_widget.dart:366:24)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)

**To Reproduce**
1. Go to the page with CreditCardWidget
2. Pop the page with the widget
3. See error

**Expected behavior**
close the stream properly on dispose, maybe we need a controller to call for inside dispose?

 - iOS (I think android too)
 - flutter_credit_card 4.0.1
 - flutter 3.16.0

**Comment by mostafaAbdelazim** [comment]
Will you please publish this to pub ? latest version on pub is 4.0.1
@ParthBaraiya @aditya-css
