### ISSUE TITLE
Validate Input card details

### ISSUE THREAD

**Issue by jawad12345A** [SimformSolutionsPvtLtd/flutter_credit_card#16]
**Validate input card details.**
Need a method which can validate card detail.  Something like that https://github.com/preethzcodez/credit_card_number_validator

**Comment by fvisticot** [comment]
It would be very useful to add credit card validation. It will remove the need to add another package

**Comment by VinceERS** [comment]
I agree since the form handles state internally it would be nice to have user feedback for instance if the credit card number is not valid it could show feedback for that particular text input.

**Comment by DevarshRanpara** [comment]
Fixed in #22.
