### ISSUE TITLE
typing in the fields do not work

### ISSUE THREAD

**Issue by williamwps** [SimformSolutionsPvtLtd/flutter_credit_card#18]
When I try to enter the card data, typing does not work ... I type, type and the character does not appear in the field.

**Comment by DevarshRanpara** [comment]
Hi @williamwps .
Can you share snippet of your plugin implementation in your app?

**Comment by vatsaltanna** [comment]
Closing this issue because of in-activty, feel free to reopen this issue if issue still persist in latest version of the package.
