### ISSUE TITLE
Is it Secure to store credit card data? 

### ISSUE THREAD

**Issue by macmatrix** [SimformSolutionsPvtLtd/flutter_credit_card#24]
Hello, I am thinking to use this widget but I am not sure it is ok to store credit card in the app. Is the data encrypted ? What should I do to make this data secure in my app?

**Comment by moobydrey** [comment]
No. do not store credit card details in the app

**Comment by jairoareyes** [comment]
I have the same question, did you use this widget?

**Comment by macmatrix** [comment]
> I have the same question, did you use this widget?

No I did not. I am actually using the stripe tool to store details online. It requires a bit of coding but it works well

**Comment by DevarshRanpara** [comment]
This is just UI to get credt card data in your app.
We are not storing any user data or card data.
