### ISSUE TITLE
Freezes on IOS Simulator SE Gen 2.

### ISSUE THREAD

**Issue by ysabuna** [SimformSolutionsPvtLtd/flutter_credit_card#29]
When accessing the screen having this package/widget, the phone freezes. This happen on IOS Simulator specifically, the 2nd Gen SE.

**Comment by DevarshRanpara** [comment]
I have tried to run example app in iOS Simulator SE Gen 2. (iOS 14.1)
Works fine in my case.
Please specify iOS version as well as if you face issue in any specific scenario.

**Comment by Bilonik** [comment]
#51

**Comment by vatsaltanna** [comment]
Closing this issue because of in activity. feel free to reopen the issue if issue still persist on latest version of the package.
