### ISSUE TITLE
Leave customizable field names

### ISSUE THREAD

**Issue by kitoide** [SimformSolutionsPvtLtd/flutter_credit_card#31]
It could be possible to change the name of the fields, for example, I live in Brazil, and all plugin field names are in English, it could be possible to change the display name of the fields

**Comment by BirjuVachhani** [comment]
@kitoide This has been already implemented by one of the contributors. However, it's not released yet. So If you want then you can use that by pointing to the master branch of this repository.

Here's the PR that added this: https://github.com/SimformSolutionsPvtLtd/flutter_credit_card/pull/30

**Comment by kitoide** [comment]
> @kitoide This has been already implemented by one of the contributors. However, it's not released yet. So If you want then you can use that by pointing to the master branch of this repository.
> 
> Here's the PR that added this: #30

I just downloaded the project and made the adjustments to the files, even made some implementations with particularities for my system
