### ISSUE TITLE
card form issue

### ISSUE THREAD

**Issue by atta1234** [SimformSolutionsPvtLtd/flutter_credit_card#33]
Hello where is this two file located or i have to create them?

import 'package:flutter_credit_card/credit_card_form.dart';
import 'package:flutter_credit_card/credit_card_model.dart';
this file show target of uri does not exist, Do i need to created it manually or it's there in package?

**Comment by DevarshRanpara** [comment]
No you don't need to create it manually,
Seems like it's catching issue in your system.
Try this[https://stackoverflow.com/a/50416453/11445644](url) solutions.
As this issue is not from package, i am closing this issue.
