### ISSUE TITLE
Add "isValid" property to CreditCardForm

### ISSUE THREAD

**Issue by funder7** [SimformSolutionsPvtLtd/flutter_credit_card#34]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I'd like to have a property, or a callback, to know if the inserted credit card data is valid or not (a sort of validation result)

**Describe alternatives you've considered**
A `ValueChanged<bool> isValid` linked to the form validation would be enough

**Comment by sanket-simform** [comment]
@funder7 will include in next release.

**Comment by Kashifalaliwala** [comment]
@funder7 This feature is supported is latest version of plugin. Kindly update it to latest version.

**Comment by DevarshRanpara** [comment]
This has been added to latest version of plugin so i am closing this issue.
