### ISSUE TITLE
Security code can be named also as "CVC", not only "CVV"

### ISSUE THREAD

**Issue by funder7** [SimformSolutionsPvtLtd/flutter_credit_card#35]
**Describe the bug**
I tought that it was a typo, but the security code can be named in both ways. If you want just close the issue, or if it has any different meaning, consider to let the dev. choose between the two options maybe? 

**Screenshots**
![immagine](https://user-images.githubusercontent.com/12503478/103443718-48fd5500-4c62-11eb-9c75-e22ec7c795ec.png)

**Comment by sanket-simform** [comment]
@funder7 we'll provide this update in next release.

**Comment by Kashifalaliwala** [comment]
@funder7 This feature is supported is latest version of plugin. Kindly update it to latest version.

**Comment by DevarshRanpara** [comment]
This has been added to latest version of plugin so i am closing this issue.
