### ISSUE TITLE
Issue Report ... Feature request

### ISSUE THREAD

**Issue by imeDevelopers** [SimformSolutionsPvtLtd/flutter_credit_card#37]
Firstly: when you click on any field the keyboard appears then disappears again and i lose the focus !, sounds like there's a timer makes setState((){}); every second .. you should fix it by letting us control the setstate steps..

Secondly: you should support dark mode, and respect the device them mode because when i convert to the dark mode in the device i see dark layer hides the content !

please do it directly, thank you.

**Comment by DevarshRanpara** [comment]
@imeDevelopers can you share gif or small video clip of issue you are facing? 
And thanks for dark mode support request, we'll look into it.

**Comment by vatsaltanna** [comment]
Closing this issue for now as not activity found. Feel free to reopen if this issue still persist in latest version of the package.
