### ISSUE TITLE
Absence of focus node in credit_card_form.dart

### ISSUE THREAD

**Issue by NikhilKamathB** [SimformSolutionsPvtLtd/flutter_credit_card#40]
**Bug**
First and foremost thanks for this package. It was very helpful for my use-case, however when I tried to customize 'credit_card_form.dart' file, I found out that there was no focus node associated with 'cardNumber' textformfield, also disposal of this node ('cardNumberNode') was missing in the 'dispose' function.

`
Container(
              padding: const EdgeInsets.symmetric(vertical: 8.0),
              margin: const EdgeInsets.only(left: 16, top: 16, right: 16),
              child: TextFormField(
                obscureText: widget.obscureNumber,
                controller: _cardNumberController,
                cursorColor: widget.cursorColor ?? themeColor,
                onEditingComplete: () {
                  FocusScope.of(context).requestFocus(expiryDateNode);
                },
                style: TextStyle(
                  color: widget.textColor,
                ),
                decoration: widget.cardNumberDecoration,
                keyboardType: TextInputType.number,
                textInputAction: TextInputAction.next,
                validator: (String value) {
                  // Validate less that 13 digits +3 white spaces
                  if (value.isEmpty || value.length < 16) {
                    return widget.numberValidationMessage;
                  }
                  return null;
                },
              ),
            ),
`

`
  @override
  void dispose() {
    cardHolderNode.dispose();
    cvvFocusNode.dispose();
    expiryDateNode.dispose();
    super.dispose();
  }
`

need to insert `focusNode: cardHolderNode,`  and `cardNumberNode.dispose();` in lib/credit_card_form.dart (lines, between 177 - 196 and lines 150 - 155 respectively as per github (master)) otherwise, the package worked fine. Feel free to close this issue if insignificant.

**Comment by vatsaltanna** [comment]
Hello @NikhilKamathB, As card number is the first field so it doesn't require focus node.

Closing this for now feel free to reopen If more information is required.
