### ISSUE TITLE
CreditCardWidget not rendering in Safari (desktop and mobile)

### ISSUE THREAD

**Issue by woshitom** [SimformSolutionsPvtLtd/flutter_credit_card#46]
CreditCardWidget is not rendering in Safari (desktop and mobile), I'm not so sure how to debug for this browser.

![Screen Shot 2564-04-28 at 07 02 04](https://user-images.githubusercontent.com/7259389/116326926-d7887a00-a7ef-11eb-85a7-3c08f6482a76.png)
![Screenshot_20210428-070048](https://user-images.githubusercontent.com/7259389/116326966-eec76780-a7ef-11eb-92a7-6afbce7520eb.png)

**Comment by emmett-deen** [comment]
Having this issue in chrome as well

**Comment by emmett-deen** [comment]
> Having this issue in chrome as well

Seems to only work with the CanvasKit web renderer

**Comment by Bilonik** [comment]
![Screen Shot 2021-07-13 at 4 08 01 PM](https://user-images.githubusercontent.com/8235588/125525217-b65f7401-f1fb-4c4e-8380-2f5f20b84f9a.png)
![Screen Shot 2021-07-13 at 4 08 09 PM](https://user-images.githubusercontent.com/8235588/125525218-d17da1fa-5f81-4a86-9cc8-fafce3398e9f.png)

**Comment by Bilonik** [comment]
#51
