### ISSUE TITLE
obscureNumber: false not works and brand do not comes

### ISSUE THREAD

**Issue by marcosradix** [SimformSolutionsPvtLtd/flutter_credit_card#48]
I am using the package but this values no works well:
- obscureNumber: false. not works
-  brand = creditCardModel.brand. brand always comes blank

**Comment by kashifalaliwala-simformsolutions** [comment]
@marcosradix Can you share snippet & screenshot of your implementation where obscureNumber & brand doesn't work.

**Comment by Kashifalaliwala** [comment]
@marcosradix  Can you share snippet & screenshot of your implementation where obscureNumber & brand doesn't work.

**Comment by RageshAntony** [comment]
> @marcosradix Can you share snippet & screenshot of your implementation where obscureNumber & brand doesn't work.

I am getting same error 

Just used the sample code in the Docs and cardModel.brand is always blank for all cards !!!

**Comment by vatsaltanna** [comment]
@RageshAntony Brand name issue has been solved but `obscureNumber: false. not works` is not reproducible so I would suggest to try this with latest version and if the issue still persist in your code then please create the new issue with code snippet that will be very helpful for us. 

Thanks
