### ISSUE TITLE
I can't change label color on floating. 

### ISSUE THREAD

**Issue by omerbyrk** [SimformSolutionsPvtLtd/flutter_credit_card#54]
Hi, my problem is changing the label color on floating mode. The default floating label color is blue and I could'nt change it.  

Here it is how my credit card form looks. 
![Screen Shot 2021-07-21 at 14 18 27](https://user-images.githubusercontent.com/23620744/126482212-2483b35c-7156-4868-86d0-d045637bef6b.png)

Here is my source code

`import 'package:flutter/material.dart';
import 'package:flutter_credit_card/credit_card_model.dart';
import 'package:flutter_credit_card/flutter_credit_card.dart';
import 'package:get/get.dart';
import 'package:mawqeay/helper/ui_helper.dart';

import '../../../theme.dart';

class CodeCreditCardPayment extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return CodeCreditCardPaymentState();
  }
}

class CodeCreditCardPaymentState extends State<CodeCreditCardPayment> {
  String cardNumber = '';
  String expiryDate = '';
  String cardHolderName = '';
  String cvvCode = '';
  bool isCvvFocused = false;
  final GlobalKey<FormState> formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    OutlineInputBorder _inputBorder = OutlineInputBorder(
        borderSide: BorderSide(
          color: inputBorderColor,
          width: 1.0,
        ),
        borderRadius: widget.borderRadius8,
        gapPadding: 4.0);
    return Scaffold(
      resizeToAvoidBottomInset: true,
      body: SafeArea(
        child: Column(
          children: <Widget>[
            CreditCardWidget(
              cardNumber: cardNumber,
              expiryDate: expiryDate,
              cardHolderName: cardHolderName,
              cvvCode: cvvCode,
              showBackView: isCvvFocused,
              obscureCardNumber: true,
              obscureCardCvv: true,
              cardBgColor: Get.theme.primaryColor,
            ),
            Expanded(
              child: SingleChildScrollView(
                child: Column(
                  children: <Widget>[
                    CreditCardForm(
                      formKey: formKey,
                      obscureCvv: true,
                      obscureNumber: true,
                      cardNumber: cardNumber,
                      cvvCode: cvvCode,
                      cardHolderName: cardHolderName,
                      expiryDate: expiryDate,
                      themeColor: Get.theme.primaryColor,
                      cardNumberDecoration: InputDecoration(
                        border: _inputBorder,
                        floatingLabelBehavior: FloatingLabelBehavior.auto,
                        enabledBorder: _inputBorder,
                        focusedBorder: _inputBorder.copyWith(
                            borderSide: BorderSide(
                                width: 2.0, color: Get.theme.primaryColor)),
                        labelText: 'Number',
                        hintText: 'XXXX XXXX XXXX XXXX',
                      ),
                      expiryDateDecoration: InputDecoration(
                        border: _inputBorder,
                        enabledBorder: _inputBorder,
                        focusedBorder: _inputBorder.copyWith(
                            borderSide: BorderSide(
                                width: 2.0, color: Get.theme.primaryColor)),
                        labelText: 'Expired Date',
                        hintText: 'XX/XX',
                      ),
                      cvvCodeDecoration: InputDecoration(
                        border: _inputBorder,
                        enabledBorder: _inputBorder,
                        focusedBorder: _inputBorder.copyWith(
                            borderSide: BorderSide(
                                width: 2.0, color: Get.theme.primaryColor)),
                        labelText: 'CVV',
                        hintText: 'XXX',
                      ),
                      cardHolderDecoration: InputDecoration(
                        border: _inputBorder,
                        enabledBorder: _inputBorder,
                        focusedBorder: _inputBorder.copyWith(
                            borderSide: BorderSide(
                                width: 2.0, color: Get.theme.primaryColor)),
                        labelText: 'Card Holder',
                      ),
                      onCreditCardModelChange: onCreditCardModelChange,
                    ),
                    ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        shape: RoundedRectangleBorder(
                          borderRadius: widget.borderRadius8,
                        ),
                        primary: Get.theme.primaryColor,
                      ),
                      child: Container(
                        margin: const EdgeInsets.all(8),
                        child: const Text(
                          'Continue',
                          style: TextStyle(
                            color: Colors.white,
                            fontFamily: 'halter',
                            fontSize: 14,
                            package: 'flutter_credit_card',
                          ),
                        ),
                      ),
                      onPressed: () {
                        /*if (formKey.currentState!.validate()) {
                            print('valid!');
                          } else {
                            print('invalid!');
                          }*/
                      },
                    )
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void onCreditCardModelChange(CreditCardModel? creditCardModel) {
    setState(() {
      cardNumber = creditCardModel!.cardNumber;
      expiryDate = creditCardModel.expiryDate;
      cardHolderName = creditCardModel.cardHolderName;
      cvvCode = creditCardModel.cvvCode;
      isCvvFocused = creditCardModel.isCvvFocused;
    });
  }
}
`
Thanks!

**Comment by livintan** [comment]
Hi you can update using labelStyle

labelStyle: TextStyle(color: Colors.black),
