### ISSUE TITLE
Flutter web issue

### ISSUE THREAD

**Issue by bibash28** [SimformSolutionsPvtLtd/flutter_credit_card#58]
transform.setEntry(3, 2, 0.001);
transform.rotateY(animation.value);

This transformation is giving following issue in latest flutter web:
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention

**Comment by SamuelMauricioL** [comment]
Hi, I was also thinking of using this library for Flutter Web. I would appreciate if you could detail how to replicate the error. Maybe we can do a pull request.

**Comment by wytex** [comment]
Hello same problem here with CreditCardWidget on flutter Web

**Comment by bibash28** [comment]
Error goes away in release mode.
