### ISSUE TITLE
Adding customization to any validator of a TextField

### ISSUE THREAD

**Issue by omargobran** [SimformSolutionsPvtLtd/flutter_credit_card#86]
At first, I wanted to find a way to somehow trigger showing the error message of Card Number TextField but couldn't so then I wanted to add an extra control or validation to the card number input but didn't find a possible way, unfortunately. Because the validator is directly written inside the TextField and not available for customization.

I would like to find a way where I can 
1. Add a custom validator to each TextField.
2. Add a bool value to the validator.
3. Make my own check/control in my app and somehow be able to trigger showing the error message for any TextField.

**Comment by DhavalRKansara** [comment]
Hi @omargobran  Thanks for the suggestion, We'll consider this enhancement in the next feature bucket. Also, we are open for contribution as well.
